### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by mrgreywater** [mapbox/earcut.hpp#26]
The algorithm looks like it could be made to run on multiple threads concurrently relatively easily. (By splitting the linked list into multiple seperate lists, and trying to split off ears in parallel). This would mean that the codebase diverges from earcut.js even more, but may lead to significant performance improvements.

**Comment by mourner** [comment]
That's an interesting idea. In theory we could change the algorithm to the following:

1. eliminate holes
2. subdivide the polygon into N parts (e.g. 4) by looking for valid diagonals that split a polygon into approximately equal parts
3. process each part independently
4. aggregate the results

The 2nd step needs some thought to do it efficiently... Also there should be some heuristic to determine whether the overhead is worth it (e.g. reduce threading for shapes with smaller number of points).

**Comment by jfirebaugh** [comment]
[mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native), the downstream package for which earcut.hpp was first written, already implements multithreading at a higher level. It has a number of worker threads, and work is split up between them on a tile-by-tile basis. Earcut is one part of this work, but there are other parts of the processing which also benefit from multithreading. Parallelization inside the earcut library itself would therefore be a pessimization for mapbox-gl-native because it would add thread management overhead without there being unused CPU resources to benefit from.

I would think that this is the case with most uses of earcut: that it's more efficient and more architecturally sound to let the downstream consumer handle parallelizing across multiple polygons, than to micro-parallelize earcutting a single polygon.

**Comment by mourner** [comment]
Great point John, thinking about it, I agree with this completely. It's much better to parallelize across multiple polygons than to introduce the complexity of thread handling within single polygon processing.
