### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by springmeyer** [mapbox/earcut.hpp#51]
Now that https://github.com/mapbox/earcut.hpp/pull/49 and https://github.com/mapbox/earcut.hpp/issues/48 are fixed, let's do a release.

I propose making it v0.12.2 and cutting it asap.

Anyone have reservations? /cc @mourner @jfirebaugh @kkaefer @mrgreywater?

**Comment by mrgreywater** [comment]
As far as I know, earcut.hpp just uses the version number from earcut.js. Since it's a header-only library, there are no binaries to be compiled for a release either. If you want to increase the version number, it has to be done over at earcut.js first. 
Apart from that, you can consider everything that's on the Master branch as release.

**Comment by mourner** [comment]
No, earcut.hpp follows its own version scheme — see https://github.com/mapbox/earcut.hpp/releases vs https://github.com/mapbox/earcut/releases

**Comment by mourner** [comment]
That was done https://github.com/mapbox/earcut.hpp/releases
