### ISSUE TITLE
Clang-Tidy static analysis warning: dereference of a null pointer

### ISSUE THREAD

**Issue by 0xb8** [mapbox/earcut.hpp#85]
See warning message here: https://godbolt.org/z/dA9tMw (give it a few seconds, static analysis is somewhat slow).

I can silence the warning by adding `assert(p && p->next)` in [earcut.hpp:235](https://github.com/mapbox/earcut.hpp/blob/master/include/mapbox/earcut.hpp#L235), and it doesn't trigger on my dataset, but I'm not familiar enough with the code to be certain there's no actual bug there.

In any case, thank you for this great library!

**Comment by mrgreywater** [comment]
I think the bug is that it should be:
`if (!end) end = start->next;` instead of the current `if (!end) end = start;` [earcut.hpp#L229](https://github.com/mapbox/earcut.hpp/blob/master/include/mapbox/earcut.hpp#L229), otherwise the while loop in the same funtion iterates outside the range of (start, end)

**Comment by mourner** [comment]
@mrgreywater no, I think it's correct — if you don't provide the `end` argument, `filterPoints` is supposed to go through the whole ring instead of stopping immediately. You can also see how it breaks a bunch of tests.

We could add an assert — `p->next` can't really be `null` since all rings are circularly connected linked lists once they're created.
